import "/public/assets/css/root-variables.css" /* Import the root variables first */
import "/public/assets/css/css-variable-guarantees.css" /* Ensure CSS variables have fallbacks */
import "/public/assets/css/bootstrap.min.css"
import "/public/assets/css/all.min.css"
import "/public/assets/css/magnific-popup.css"
import "/public/assets/css/nice-select.css"
import "/public/assets/css/swiper.min.css"
import "/public/assets/css/aos.css"
import "/public/assets/css/globals.css" 
import "/public/assets/css/main.css"
import "/public/assets/css/spline-custom.css"
import "/public/assets/css/custom-colors.css"
import "/public/assets/css/hero-gradient.css"
import "/public/assets/css/spline-fixes.css"
import "/public/assets/css/color-palette.css"
import "/public/assets/css/form-colors.css"
import "/public/assets/css/card-colors.css"
import "/public/assets/css/footer-colors.css"
import "/public/assets/css/nav-colors.css"
import "/public/assets/css/button-colors.css"
import "/public/assets/css/custom-bg.css"
import "/public/assets/css/tailwind-colors.css" /* Import Tailwind utilities */
import "/public/assets/css/hover-effects.css" /* Import hover effects last to override other styles */
import { Manrope, Plus_Jakarta_Sans } from 'next/font/google'
import dynamic from 'next/dynamic'



const manrope = Manrope({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--manrope",
    display: 'swap',
})
const jakarta = Plus_Jakarta_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--jakarta",
    display: 'swap',
})
export const metadata = {
    title: 'Xstar - Digital Agency Next.js Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${manrope.variable} ${jakarta.variable} position-relative bg2-clr`}>
                {children}
                
                
            </body>
        </html>
    )
}
